# This workflow will upload a Python Package

name: Upload Python Package

on:
  release:
    types: [published]
  
  # Allows you to run workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: "Set up Python"
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
        
    - name: "Install dependencies"
      run: |
        python -m pip install --upgrade pip
        pip install build twine bumpver
        
    - name: "Bump package version"
      run: |
        python3 -m bumpver --patch

    - name: "Builds and uploads to PyPI"
      run: |
        python3 -m build
        python3 -m twine upload dist/*
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
